# Generated by Django 2.2.13 on 2020-06-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietinfo',
            name='name',
            field=models.CharField(default='username', max_length=1000),
        ),
    ]
