# Generated by Django 2.2.13 on 2020-06-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dietinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieteaten',
            name='name',
            field=models.CharField(default='username', max_length=1000),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='username', max_length=1000),
        ),
        migrations.AlterField(
            model_name='dieteaten',
            name='dietNameQuantity',
            field=models.CharField(choices=[('Avocado', 'Avocado::1'), ('Rice', 'Rice::1')], max_length=10000),
        ),
    ]
